FROM golang:1.22-alpine

WORKDIR /app

COPY go.mod ./
RUN go mod tidy

# Install envsubst
RUN apk add --no-cache gettext

COPY . .
RUN go build -o main .

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]